// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: olympus/orchestration/v1/orchestration.proto

package orchestrationv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Messaging Messages
type PublishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_olympus_orchestration_v1_orchestration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_olympus_orchestration_v1_orchestration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_olympus_orchestration_v1_orchestration_proto_rawDescGZIP(), []int{0}
}

func (x *PublishRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *PublishRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PublishResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishResponse) Reset() {
	*x = PublishResponse{}
	mi := &file_olympus_orchestration_v1_orchestration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResponse) ProtoMessage() {}

func (x *PublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_olympus_orchestration_v1_orchestration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResponse.ProtoReflect.Descriptor instead.
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return file_olympus_orchestration_v1_orchestration_proto_rawDescGZIP(), []int{1}
}

func (x *PublishResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

// Task Messages
type TaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queue         string                 `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	Payload       string                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	mi := &file_olympus_orchestration_v1_orchestration_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_olympus_orchestration_v1_orchestration_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_olympus_orchestration_v1_orchestration_proto_rawDescGZIP(), []int{2}
}

func (x *TaskRequest) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *TaskRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type TaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResponse) Reset() {
	*x = TaskResponse{}
	mi := &file_olympus_orchestration_v1_orchestration_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResponse) ProtoMessage() {}

func (x *TaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_olympus_orchestration_v1_orchestration_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResponse.ProtoReflect.Descriptor instead.
func (*TaskResponse) Descriptor() ([]byte, []int) {
	return file_olympus_orchestration_v1_orchestration_proto_rawDescGZIP(), []int{3}
}

func (x *TaskResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

// Scheduler Messages
type JobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Schedule      string                 `protobuf:"bytes,2,opt,name=schedule,proto3" json:"schedule,omitempty"`
	Target        string                 `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobRequest) Reset() {
	*x = JobRequest{}
	mi := &file_olympus_orchestration_v1_orchestration_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobRequest) ProtoMessage() {}

func (x *JobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_olympus_orchestration_v1_orchestration_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobRequest.ProtoReflect.Descriptor instead.
func (*JobRequest) Descriptor() ([]byte, []int) {
	return file_olympus_orchestration_v1_orchestration_proto_rawDescGZIP(), []int{4}
}

func (x *JobRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *JobRequest) GetSchedule() string {
	if x != nil {
		return x.Schedule
	}
	return ""
}

func (x *JobRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

type JobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobResponse) Reset() {
	*x = JobResponse{}
	mi := &file_olympus_orchestration_v1_orchestration_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobResponse) ProtoMessage() {}

func (x *JobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_olympus_orchestration_v1_orchestration_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobResponse.ProtoReflect.Descriptor instead.
func (*JobResponse) Descriptor() ([]byte, []int) {
	return file_olympus_orchestration_v1_orchestration_proto_rawDescGZIP(), []int{5}
}

func (x *JobResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

// Workflow Messages
type WorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	InputJson     string                 `protobuf:"bytes,2,opt,name=input_json,json=inputJson,proto3" json:"input_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowRequest) Reset() {
	*x = WorkflowRequest{}
	mi := &file_olympus_orchestration_v1_orchestration_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowRequest) ProtoMessage() {}

func (x *WorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_olympus_orchestration_v1_orchestration_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowRequest.ProtoReflect.Descriptor instead.
func (*WorkflowRequest) Descriptor() ([]byte, []int) {
	return file_olympus_orchestration_v1_orchestration_proto_rawDescGZIP(), []int{6}
}

func (x *WorkflowRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *WorkflowRequest) GetInputJson() string {
	if x != nil {
		return x.InputJson
	}
	return ""
}

type WorkflowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OutputJson    string                 `protobuf:"bytes,1,opt,name=output_json,json=outputJson,proto3" json:"output_json,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowResponse) Reset() {
	*x = WorkflowResponse{}
	mi := &file_olympus_orchestration_v1_orchestration_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowResponse) ProtoMessage() {}

func (x *WorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_olympus_orchestration_v1_orchestration_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowResponse.ProtoReflect.Descriptor instead.
func (*WorkflowResponse) Descriptor() ([]byte, []int) {
	return file_olympus_orchestration_v1_orchestration_proto_rawDescGZIP(), []int{7}
}

func (x *WorkflowResponse) GetOutputJson() string {
	if x != nil {
		return x.OutputJson
	}
	return ""
}

func (x *WorkflowResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

var File_olympus_orchestration_v1_orchestration_proto protoreflect.FileDescriptor

const file_olympus_orchestration_v1_orchestration_proto_rawDesc = "" +
	"\n" +
	",olympus/orchestration/v1/orchestration.proto\x12\x18olympus.orchestration.v1\":\n" +
	"\x0ePublishRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"0\n" +
	"\x0fPublishResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\"=\n" +
	"\vTaskRequest\x12\x14\n" +
	"\x05queue\x18\x01 \x01(\tR\x05queue\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\"'\n" +
	"\fTaskResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"T\n" +
	"\n" +
	"JobRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bschedule\x18\x02 \x01(\tR\bschedule\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\"$\n" +
	"\vJobResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"Q\n" +
	"\x0fWorkflowRequest\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12\x1d\n" +
	"\n" +
	"input_json\x18\x02 \x01(\tR\tinputJson\"I\n" +
	"\x10WorkflowResponse\x12\x1f\n" +
	"\voutput_json\x18\x01 \x01(\tR\n" +
	"outputJson\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state2\x97\x03\n" +
	"\x14OrchestrationService\x12^\n" +
	"\aPublish\x12(.olympus.orchestration.v1.PublishRequest\x1a).olympus.orchestration.v1.PublishResponse\x12[\n" +
	"\n" +
	"CreateTask\x12%.olympus.orchestration.v1.TaskRequest\x1a&.olympus.orchestration.v1.TaskResponse\x12X\n" +
	"\tCreateJob\x12$.olympus.orchestration.v1.JobRequest\x1a%.olympus.orchestration.v1.JobResponse\x12h\n" +
	"\x0fExecuteWorkflow\x12).olympus.orchestration.v1.WorkflowRequest\x1a*.olympus.orchestration.v1.WorkflowResponseBzZxOlympusGCP-Orchestration/40000-Communication-Contracts/430-Protocol-Definitions/000-gen/orchestration/v1;orchestrationv1b\x06proto3"

var (
	file_olympus_orchestration_v1_orchestration_proto_rawDescOnce sync.Once
	file_olympus_orchestration_v1_orchestration_proto_rawDescData []byte
)

func file_olympus_orchestration_v1_orchestration_proto_rawDescGZIP() []byte {
	file_olympus_orchestration_v1_orchestration_proto_rawDescOnce.Do(func() {
		file_olympus_orchestration_v1_orchestration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_olympus_orchestration_v1_orchestration_proto_rawDesc), len(file_olympus_orchestration_v1_orchestration_proto_rawDesc)))
	})
	return file_olympus_orchestration_v1_orchestration_proto_rawDescData
}

var file_olympus_orchestration_v1_orchestration_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_olympus_orchestration_v1_orchestration_proto_goTypes = []any{
	(*PublishRequest)(nil),   // 0: olympus.orchestration.v1.PublishRequest
	(*PublishResponse)(nil),  // 1: olympus.orchestration.v1.PublishResponse
	(*TaskRequest)(nil),      // 2: olympus.orchestration.v1.TaskRequest
	(*TaskResponse)(nil),     // 3: olympus.orchestration.v1.TaskResponse
	(*JobRequest)(nil),       // 4: olympus.orchestration.v1.JobRequest
	(*JobResponse)(nil),      // 5: olympus.orchestration.v1.JobResponse
	(*WorkflowRequest)(nil),  // 6: olympus.orchestration.v1.WorkflowRequest
	(*WorkflowResponse)(nil), // 7: olympus.orchestration.v1.WorkflowResponse
}
var file_olympus_orchestration_v1_orchestration_proto_depIdxs = []int32{
	0, // 0: olympus.orchestration.v1.OrchestrationService.Publish:input_type -> olympus.orchestration.v1.PublishRequest
	2, // 1: olympus.orchestration.v1.OrchestrationService.CreateTask:input_type -> olympus.orchestration.v1.TaskRequest
	4, // 2: olympus.orchestration.v1.OrchestrationService.CreateJob:input_type -> olympus.orchestration.v1.JobRequest
	6, // 3: olympus.orchestration.v1.OrchestrationService.ExecuteWorkflow:input_type -> olympus.orchestration.v1.WorkflowRequest
	1, // 4: olympus.orchestration.v1.OrchestrationService.Publish:output_type -> olympus.orchestration.v1.PublishResponse
	3, // 5: olympus.orchestration.v1.OrchestrationService.CreateTask:output_type -> olympus.orchestration.v1.TaskResponse
	5, // 6: olympus.orchestration.v1.OrchestrationService.CreateJob:output_type -> olympus.orchestration.v1.JobResponse
	7, // 7: olympus.orchestration.v1.OrchestrationService.ExecuteWorkflow:output_type -> olympus.orchestration.v1.WorkflowResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_olympus_orchestration_v1_orchestration_proto_init() }
func file_olympus_orchestration_v1_orchestration_proto_init() {
	if File_olympus_orchestration_v1_orchestration_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_olympus_orchestration_v1_orchestration_proto_rawDesc), len(file_olympus_orchestration_v1_orchestration_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_olympus_orchestration_v1_orchestration_proto_goTypes,
		DependencyIndexes: file_olympus_orchestration_v1_orchestration_proto_depIdxs,
		MessageInfos:      file_olympus_orchestration_v1_orchestration_proto_msgTypes,
	}.Build()
	File_olympus_orchestration_v1_orchestration_proto = out.File
	file_olympus_orchestration_v1_orchestration_proto_goTypes = nil
	file_olympus_orchestration_v1_orchestration_proto_depIdxs = nil
}
