// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: olympus/orchestration/v1/orchestration.proto

package orchestrationv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_olympus_orchestration_v1_orchestration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_olympus_orchestration_v1_orchestration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_olympus_orchestration_v1_orchestration_proto_rawDescGZIP(), []int{0}
}

func (x *StatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Messaging Messages
type PublishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_olympus_orchestration_v1_orchestration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_olympus_orchestration_v1_orchestration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_olympus_orchestration_v1_orchestration_proto_rawDescGZIP(), []int{1}
}

func (x *PublishRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *PublishRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PublishResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishResponse) Reset() {
	*x = PublishResponse{}
	mi := &file_olympus_orchestration_v1_orchestration_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResponse) ProtoMessage() {}

func (x *PublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_olympus_orchestration_v1_orchestration_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResponse.ProtoReflect.Descriptor instead.
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return file_olympus_orchestration_v1_orchestration_proto_rawDescGZIP(), []int{2}
}

func (x *PublishResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type TopicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicId       string                 `protobuf:"bytes,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicRequest) Reset() {
	*x = TopicRequest{}
	mi := &file_olympus_orchestration_v1_orchestration_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicRequest) ProtoMessage() {}

func (x *TopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_olympus_orchestration_v1_orchestration_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicRequest.ProtoReflect.Descriptor instead.
func (*TopicRequest) Descriptor() ([]byte, []int) {
	return file_olympus_orchestration_v1_orchestration_proto_rawDescGZIP(), []int{3}
}

func (x *TopicRequest) GetTopicId() string {
	if x != nil {
		return x.TopicId
	}
	return ""
}

type SubscriptionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId string                 `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	TopicId        string                 `protobuf:"bytes,2,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubscriptionRequest) Reset() {
	*x = SubscriptionRequest{}
	mi := &file_olympus_orchestration_v1_orchestration_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionRequest) ProtoMessage() {}

func (x *SubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_olympus_orchestration_v1_orchestration_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionRequest.ProtoReflect.Descriptor instead.
func (*SubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_olympus_orchestration_v1_orchestration_proto_rawDescGZIP(), []int{4}
}

func (x *SubscriptionRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *SubscriptionRequest) GetTopicId() string {
	if x != nil {
		return x.TopicId
	}
	return ""
}

// Task Messages
type TaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queue         string                 `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	Payload       string                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	mi := &file_olympus_orchestration_v1_orchestration_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_olympus_orchestration_v1_orchestration_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_olympus_orchestration_v1_orchestration_proto_rawDescGZIP(), []int{5}
}

func (x *TaskRequest) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *TaskRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type TaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResponse) Reset() {
	*x = TaskResponse{}
	mi := &file_olympus_orchestration_v1_orchestration_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResponse) ProtoMessage() {}

func (x *TaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_olympus_orchestration_v1_orchestration_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResponse.ProtoReflect.Descriptor instead.
func (*TaskResponse) Descriptor() ([]byte, []int) {
	return file_olympus_orchestration_v1_orchestration_proto_rawDescGZIP(), []int{6}
}

func (x *TaskResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

// Scheduler Messages
type JobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Schedule      string                 `protobuf:"bytes,2,opt,name=schedule,proto3" json:"schedule,omitempty"`
	Target        string                 `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobRequest) Reset() {
	*x = JobRequest{}
	mi := &file_olympus_orchestration_v1_orchestration_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobRequest) ProtoMessage() {}

func (x *JobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_olympus_orchestration_v1_orchestration_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobRequest.ProtoReflect.Descriptor instead.
func (*JobRequest) Descriptor() ([]byte, []int) {
	return file_olympus_orchestration_v1_orchestration_proto_rawDescGZIP(), []int{7}
}

func (x *JobRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *JobRequest) GetSchedule() string {
	if x != nil {
		return x.Schedule
	}
	return ""
}

func (x *JobRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

type JobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobResponse) Reset() {
	*x = JobResponse{}
	mi := &file_olympus_orchestration_v1_orchestration_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobResponse) ProtoMessage() {}

func (x *JobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_olympus_orchestration_v1_orchestration_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobResponse.ProtoReflect.Descriptor instead.
func (*JobResponse) Descriptor() ([]byte, []int) {
	return file_olympus_orchestration_v1_orchestration_proto_rawDescGZIP(), []int{8}
}

func (x *JobResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

// Workflow Messages
type WorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	InputJson     string                 `protobuf:"bytes,2,opt,name=input_json,json=inputJson,proto3" json:"input_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowRequest) Reset() {
	*x = WorkflowRequest{}
	mi := &file_olympus_orchestration_v1_orchestration_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowRequest) ProtoMessage() {}

func (x *WorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_olympus_orchestration_v1_orchestration_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowRequest.ProtoReflect.Descriptor instead.
func (*WorkflowRequest) Descriptor() ([]byte, []int) {
	return file_olympus_orchestration_v1_orchestration_proto_rawDescGZIP(), []int{9}
}

func (x *WorkflowRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *WorkflowRequest) GetInputJson() string {
	if x != nil {
		return x.InputJson
	}
	return ""
}

type WorkflowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OutputJson    string                 `protobuf:"bytes,1,opt,name=output_json,json=outputJson,proto3" json:"output_json,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowResponse) Reset() {
	*x = WorkflowResponse{}
	mi := &file_olympus_orchestration_v1_orchestration_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowResponse) ProtoMessage() {}

func (x *WorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_olympus_orchestration_v1_orchestration_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowResponse.ProtoReflect.Descriptor instead.
func (*WorkflowResponse) Descriptor() ([]byte, []int) {
	return file_olympus_orchestration_v1_orchestration_proto_rawDescGZIP(), []int{10}
}

func (x *WorkflowResponse) GetOutputJson() string {
	if x != nil {
		return x.OutputJson
	}
	return ""
}

func (x *WorkflowResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

// Eventarc Messages
type TriggerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TriggerId     string                 `protobuf:"bytes,1,opt,name=trigger_id,json=triggerId,proto3" json:"trigger_id,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`                                                      // e.g. "GCS_OBJECT_FINALIZE"
	TargetUrl     string                 `protobuf:"bytes,3,opt,name=target_url,json=targetUrl,proto3" json:"target_url,omitempty"`                                                      // The HTTP endpoint to call
	Filters       map[string]string      `protobuf:"bytes,4,rep,name=filters,proto3" json:"filters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // e.g. {"bucket": "my-bucket"}
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerRequest) Reset() {
	*x = TriggerRequest{}
	mi := &file_olympus_orchestration_v1_orchestration_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerRequest) ProtoMessage() {}

func (x *TriggerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_olympus_orchestration_v1_orchestration_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerRequest.ProtoReflect.Descriptor instead.
func (*TriggerRequest) Descriptor() ([]byte, []int) {
	return file_olympus_orchestration_v1_orchestration_proto_rawDescGZIP(), []int{11}
}

func (x *TriggerRequest) GetTriggerId() string {
	if x != nil {
		return x.TriggerId
	}
	return ""
}

func (x *TriggerRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *TriggerRequest) GetTargetUrl() string {
	if x != nil {
		return x.TargetUrl
	}
	return ""
}

func (x *TriggerRequest) GetFilters() map[string]string {
	if x != nil {
		return x.Filters
	}
	return nil
}

var File_olympus_orchestration_v1_orchestration_proto protoreflect.FileDescriptor

const file_olympus_orchestration_v1_orchestration_proto_rawDesc = "" +
	"\n" +
	",olympus/orchestration/v1/orchestration.proto\x12\x18olympus.orchestration.v1\"*\n" +
	"\x0eStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\":\n" +
	"\x0ePublishRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"0\n" +
	"\x0fPublishResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\")\n" +
	"\fTopicRequest\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\tR\atopicId\"Y\n" +
	"\x13SubscriptionRequest\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\x12\x19\n" +
	"\btopic_id\x18\x02 \x01(\tR\atopicId\"=\n" +
	"\vTaskRequest\x12\x14\n" +
	"\x05queue\x18\x01 \x01(\tR\x05queue\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\"'\n" +
	"\fTaskResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"T\n" +
	"\n" +
	"JobRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bschedule\x18\x02 \x01(\tR\bschedule\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\"$\n" +
	"\vJobResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"Q\n" +
	"\x0fWorkflowRequest\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12\x1d\n" +
	"\n" +
	"input_json\x18\x02 \x01(\tR\tinputJson\"I\n" +
	"\x10WorkflowResponse\x12\x1f\n" +
	"\voutput_json\x18\x01 \x01(\tR\n" +
	"outputJson\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\"\xfa\x01\n" +
	"\x0eTriggerRequest\x12\x1d\n" +
	"\n" +
	"trigger_id\x18\x01 \x01(\tR\ttriggerId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x1d\n" +
	"\n" +
	"target_url\x18\x03 \x01(\tR\ttargetUrl\x12O\n" +
	"\afilters\x18\x04 \x03(\v25.olympus.orchestration.v1.TriggerRequest.FiltersEntryR\afilters\x1a:\n" +
	"\fFiltersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xce\x05\n" +
	"\x14OrchestrationService\x12^\n" +
	"\aPublish\x12(.olympus.orchestration.v1.PublishRequest\x1a).olympus.orchestration.v1.PublishResponse\x12_\n" +
	"\vCreateTopic\x12&.olympus.orchestration.v1.TopicRequest\x1a(.olympus.orchestration.v1.StatusResponse\x12m\n" +
	"\x12CreateSubscription\x12-.olympus.orchestration.v1.SubscriptionRequest\x1a(.olympus.orchestration.v1.StatusResponse\x12[\n" +
	"\n" +
	"CreateTask\x12%.olympus.orchestration.v1.TaskRequest\x1a&.olympus.orchestration.v1.TaskResponse\x12X\n" +
	"\tCreateJob\x12$.olympus.orchestration.v1.JobRequest\x1a%.olympus.orchestration.v1.JobResponse\x12h\n" +
	"\x0fExecuteWorkflow\x12).olympus.orchestration.v1.WorkflowRequest\x1a*.olympus.orchestration.v1.WorkflowResponse\x12e\n" +
	"\x0fRegisterTrigger\x12(.olympus.orchestration.v1.TriggerRequest\x1a(.olympus.orchestration.v1.StatusResponseBzZxOlympusGCP-Orchestration/40000-Communication-Contracts/430-Protocol-Definitions/000-gen/orchestration/v1;orchestrationv1b\x06proto3"

var (
	file_olympus_orchestration_v1_orchestration_proto_rawDescOnce sync.Once
	file_olympus_orchestration_v1_orchestration_proto_rawDescData []byte
)

func file_olympus_orchestration_v1_orchestration_proto_rawDescGZIP() []byte {
	file_olympus_orchestration_v1_orchestration_proto_rawDescOnce.Do(func() {
		file_olympus_orchestration_v1_orchestration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_olympus_orchestration_v1_orchestration_proto_rawDesc), len(file_olympus_orchestration_v1_orchestration_proto_rawDesc)))
	})
	return file_olympus_orchestration_v1_orchestration_proto_rawDescData
}

var file_olympus_orchestration_v1_orchestration_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_olympus_orchestration_v1_orchestration_proto_goTypes = []any{
	(*StatusResponse)(nil),      // 0: olympus.orchestration.v1.StatusResponse
	(*PublishRequest)(nil),      // 1: olympus.orchestration.v1.PublishRequest
	(*PublishResponse)(nil),     // 2: olympus.orchestration.v1.PublishResponse
	(*TopicRequest)(nil),        // 3: olympus.orchestration.v1.TopicRequest
	(*SubscriptionRequest)(nil), // 4: olympus.orchestration.v1.SubscriptionRequest
	(*TaskRequest)(nil),         // 5: olympus.orchestration.v1.TaskRequest
	(*TaskResponse)(nil),        // 6: olympus.orchestration.v1.TaskResponse
	(*JobRequest)(nil),          // 7: olympus.orchestration.v1.JobRequest
	(*JobResponse)(nil),         // 8: olympus.orchestration.v1.JobResponse
	(*WorkflowRequest)(nil),     // 9: olympus.orchestration.v1.WorkflowRequest
	(*WorkflowResponse)(nil),    // 10: olympus.orchestration.v1.WorkflowResponse
	(*TriggerRequest)(nil),      // 11: olympus.orchestration.v1.TriggerRequest
	nil,                         // 12: olympus.orchestration.v1.TriggerRequest.FiltersEntry
}
var file_olympus_orchestration_v1_orchestration_proto_depIdxs = []int32{
	12, // 0: olympus.orchestration.v1.TriggerRequest.filters:type_name -> olympus.orchestration.v1.TriggerRequest.FiltersEntry
	1,  // 1: olympus.orchestration.v1.OrchestrationService.Publish:input_type -> olympus.orchestration.v1.PublishRequest
	3,  // 2: olympus.orchestration.v1.OrchestrationService.CreateTopic:input_type -> olympus.orchestration.v1.TopicRequest
	4,  // 3: olympus.orchestration.v1.OrchestrationService.CreateSubscription:input_type -> olympus.orchestration.v1.SubscriptionRequest
	5,  // 4: olympus.orchestration.v1.OrchestrationService.CreateTask:input_type -> olympus.orchestration.v1.TaskRequest
	7,  // 5: olympus.orchestration.v1.OrchestrationService.CreateJob:input_type -> olympus.orchestration.v1.JobRequest
	9,  // 6: olympus.orchestration.v1.OrchestrationService.ExecuteWorkflow:input_type -> olympus.orchestration.v1.WorkflowRequest
	11, // 7: olympus.orchestration.v1.OrchestrationService.RegisterTrigger:input_type -> olympus.orchestration.v1.TriggerRequest
	2,  // 8: olympus.orchestration.v1.OrchestrationService.Publish:output_type -> olympus.orchestration.v1.PublishResponse
	0,  // 9: olympus.orchestration.v1.OrchestrationService.CreateTopic:output_type -> olympus.orchestration.v1.StatusResponse
	0,  // 10: olympus.orchestration.v1.OrchestrationService.CreateSubscription:output_type -> olympus.orchestration.v1.StatusResponse
	6,  // 11: olympus.orchestration.v1.OrchestrationService.CreateTask:output_type -> olympus.orchestration.v1.TaskResponse
	8,  // 12: olympus.orchestration.v1.OrchestrationService.CreateJob:output_type -> olympus.orchestration.v1.JobResponse
	10, // 13: olympus.orchestration.v1.OrchestrationService.ExecuteWorkflow:output_type -> olympus.orchestration.v1.WorkflowResponse
	0,  // 14: olympus.orchestration.v1.OrchestrationService.RegisterTrigger:output_type -> olympus.orchestration.v1.StatusResponse
	8,  // [8:15] is the sub-list for method output_type
	1,  // [1:8] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_olympus_orchestration_v1_orchestration_proto_init() }
func file_olympus_orchestration_v1_orchestration_proto_init() {
	if File_olympus_orchestration_v1_orchestration_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_olympus_orchestration_v1_orchestration_proto_rawDesc), len(file_olympus_orchestration_v1_orchestration_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_olympus_orchestration_v1_orchestration_proto_goTypes,
		DependencyIndexes: file_olympus_orchestration_v1_orchestration_proto_depIdxs,
		MessageInfos:      file_olympus_orchestration_v1_orchestration_proto_msgTypes,
	}.Build()
	File_olympus_orchestration_v1_orchestration_proto = out.File
	file_olympus_orchestration_v1_orchestration_proto_goTypes = nil
	file_olympus_orchestration_v1_orchestration_proto_depIdxs = nil
}
