// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: olympus/orchestration/v1/orchestration.proto

package orchestrationv1connect

import (
	v1 "OlympusGCP-Orchestration/40000-Communication-Contracts/430-Protocol-Definitions/000-gen/orchestration/v1"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// OrchestrationServiceName is the fully-qualified name of the OrchestrationService service.
	OrchestrationServiceName = "olympus.orchestration.v1.OrchestrationService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// OrchestrationServicePublishProcedure is the fully-qualified name of the OrchestrationService's
	// Publish RPC.
	OrchestrationServicePublishProcedure = "/olympus.orchestration.v1.OrchestrationService/Publish"
	// OrchestrationServiceCreateTaskProcedure is the fully-qualified name of the OrchestrationService's
	// CreateTask RPC.
	OrchestrationServiceCreateTaskProcedure = "/olympus.orchestration.v1.OrchestrationService/CreateTask"
	// OrchestrationServiceCreateJobProcedure is the fully-qualified name of the OrchestrationService's
	// CreateJob RPC.
	OrchestrationServiceCreateJobProcedure = "/olympus.orchestration.v1.OrchestrationService/CreateJob"
	// OrchestrationServiceExecuteWorkflowProcedure is the fully-qualified name of the
	// OrchestrationService's ExecuteWorkflow RPC.
	OrchestrationServiceExecuteWorkflowProcedure = "/olympus.orchestration.v1.OrchestrationService/ExecuteWorkflow"
)

// OrchestrationServiceClient is a client for the olympus.orchestration.v1.OrchestrationService
// service.
type OrchestrationServiceClient interface {
	// --- Pub/Sub ---
	Publish(context.Context, *connect.Request[v1.PublishRequest]) (*connect.Response[v1.PublishResponse], error)
	// --- Cloud Tasks ---
	CreateTask(context.Context, *connect.Request[v1.TaskRequest]) (*connect.Response[v1.TaskResponse], error)
	// --- Cloud Scheduler ---
	CreateJob(context.Context, *connect.Request[v1.JobRequest]) (*connect.Response[v1.JobResponse], error)
	// --- Cloud Workflows (Expansion) ---
	ExecuteWorkflow(context.Context, *connect.Request[v1.WorkflowRequest]) (*connect.Response[v1.WorkflowResponse], error)
}

// NewOrchestrationServiceClient constructs a client for the
// olympus.orchestration.v1.OrchestrationService service. By default, it uses the Connect protocol
// with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed requests. To
// use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or connect.WithGRPCWeb()
// options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewOrchestrationServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) OrchestrationServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	orchestrationServiceMethods := v1.File_olympus_orchestration_v1_orchestration_proto.Services().ByName("OrchestrationService").Methods()
	return &orchestrationServiceClient{
		publish: connect.NewClient[v1.PublishRequest, v1.PublishResponse](
			httpClient,
			baseURL+OrchestrationServicePublishProcedure,
			connect.WithSchema(orchestrationServiceMethods.ByName("Publish")),
			connect.WithClientOptions(opts...),
		),
		createTask: connect.NewClient[v1.TaskRequest, v1.TaskResponse](
			httpClient,
			baseURL+OrchestrationServiceCreateTaskProcedure,
			connect.WithSchema(orchestrationServiceMethods.ByName("CreateTask")),
			connect.WithClientOptions(opts...),
		),
		createJob: connect.NewClient[v1.JobRequest, v1.JobResponse](
			httpClient,
			baseURL+OrchestrationServiceCreateJobProcedure,
			connect.WithSchema(orchestrationServiceMethods.ByName("CreateJob")),
			connect.WithClientOptions(opts...),
		),
		executeWorkflow: connect.NewClient[v1.WorkflowRequest, v1.WorkflowResponse](
			httpClient,
			baseURL+OrchestrationServiceExecuteWorkflowProcedure,
			connect.WithSchema(orchestrationServiceMethods.ByName("ExecuteWorkflow")),
			connect.WithClientOptions(opts...),
		),
	}
}

// orchestrationServiceClient implements OrchestrationServiceClient.
type orchestrationServiceClient struct {
	publish         *connect.Client[v1.PublishRequest, v1.PublishResponse]
	createTask      *connect.Client[v1.TaskRequest, v1.TaskResponse]
	createJob       *connect.Client[v1.JobRequest, v1.JobResponse]
	executeWorkflow *connect.Client[v1.WorkflowRequest, v1.WorkflowResponse]
}

// Publish calls olympus.orchestration.v1.OrchestrationService.Publish.
func (c *orchestrationServiceClient) Publish(ctx context.Context, req *connect.Request[v1.PublishRequest]) (*connect.Response[v1.PublishResponse], error) {
	return c.publish.CallUnary(ctx, req)
}

// CreateTask calls olympus.orchestration.v1.OrchestrationService.CreateTask.
func (c *orchestrationServiceClient) CreateTask(ctx context.Context, req *connect.Request[v1.TaskRequest]) (*connect.Response[v1.TaskResponse], error) {
	return c.createTask.CallUnary(ctx, req)
}

// CreateJob calls olympus.orchestration.v1.OrchestrationService.CreateJob.
func (c *orchestrationServiceClient) CreateJob(ctx context.Context, req *connect.Request[v1.JobRequest]) (*connect.Response[v1.JobResponse], error) {
	return c.createJob.CallUnary(ctx, req)
}

// ExecuteWorkflow calls olympus.orchestration.v1.OrchestrationService.ExecuteWorkflow.
func (c *orchestrationServiceClient) ExecuteWorkflow(ctx context.Context, req *connect.Request[v1.WorkflowRequest]) (*connect.Response[v1.WorkflowResponse], error) {
	return c.executeWorkflow.CallUnary(ctx, req)
}

// OrchestrationServiceHandler is an implementation of the
// olympus.orchestration.v1.OrchestrationService service.
type OrchestrationServiceHandler interface {
	// --- Pub/Sub ---
	Publish(context.Context, *connect.Request[v1.PublishRequest]) (*connect.Response[v1.PublishResponse], error)
	// --- Cloud Tasks ---
	CreateTask(context.Context, *connect.Request[v1.TaskRequest]) (*connect.Response[v1.TaskResponse], error)
	// --- Cloud Scheduler ---
	CreateJob(context.Context, *connect.Request[v1.JobRequest]) (*connect.Response[v1.JobResponse], error)
	// --- Cloud Workflows (Expansion) ---
	ExecuteWorkflow(context.Context, *connect.Request[v1.WorkflowRequest]) (*connect.Response[v1.WorkflowResponse], error)
}

// NewOrchestrationServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewOrchestrationServiceHandler(svc OrchestrationServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	orchestrationServiceMethods := v1.File_olympus_orchestration_v1_orchestration_proto.Services().ByName("OrchestrationService").Methods()
	orchestrationServicePublishHandler := connect.NewUnaryHandler(
		OrchestrationServicePublishProcedure,
		svc.Publish,
		connect.WithSchema(orchestrationServiceMethods.ByName("Publish")),
		connect.WithHandlerOptions(opts...),
	)
	orchestrationServiceCreateTaskHandler := connect.NewUnaryHandler(
		OrchestrationServiceCreateTaskProcedure,
		svc.CreateTask,
		connect.WithSchema(orchestrationServiceMethods.ByName("CreateTask")),
		connect.WithHandlerOptions(opts...),
	)
	orchestrationServiceCreateJobHandler := connect.NewUnaryHandler(
		OrchestrationServiceCreateJobProcedure,
		svc.CreateJob,
		connect.WithSchema(orchestrationServiceMethods.ByName("CreateJob")),
		connect.WithHandlerOptions(opts...),
	)
	orchestrationServiceExecuteWorkflowHandler := connect.NewUnaryHandler(
		OrchestrationServiceExecuteWorkflowProcedure,
		svc.ExecuteWorkflow,
		connect.WithSchema(orchestrationServiceMethods.ByName("ExecuteWorkflow")),
		connect.WithHandlerOptions(opts...),
	)
	return "/olympus.orchestration.v1.OrchestrationService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case OrchestrationServicePublishProcedure:
			orchestrationServicePublishHandler.ServeHTTP(w, r)
		case OrchestrationServiceCreateTaskProcedure:
			orchestrationServiceCreateTaskHandler.ServeHTTP(w, r)
		case OrchestrationServiceCreateJobProcedure:
			orchestrationServiceCreateJobHandler.ServeHTTP(w, r)
		case OrchestrationServiceExecuteWorkflowProcedure:
			orchestrationServiceExecuteWorkflowHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedOrchestrationServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedOrchestrationServiceHandler struct{}

func (UnimplementedOrchestrationServiceHandler) Publish(context.Context, *connect.Request[v1.PublishRequest]) (*connect.Response[v1.PublishResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("olympus.orchestration.v1.OrchestrationService.Publish is not implemented"))
}

func (UnimplementedOrchestrationServiceHandler) CreateTask(context.Context, *connect.Request[v1.TaskRequest]) (*connect.Response[v1.TaskResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("olympus.orchestration.v1.OrchestrationService.CreateTask is not implemented"))
}

func (UnimplementedOrchestrationServiceHandler) CreateJob(context.Context, *connect.Request[v1.JobRequest]) (*connect.Response[v1.JobResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("olympus.orchestration.v1.OrchestrationService.CreateJob is not implemented"))
}

func (UnimplementedOrchestrationServiceHandler) ExecuteWorkflow(context.Context, *connect.Request[v1.WorkflowRequest]) (*connect.Response[v1.WorkflowResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("olympus.orchestration.v1.OrchestrationService.ExecuteWorkflow is not implemented"))
}
